quarkus:
  log:
    console:
      enable: true
      json: false
      level: DEBUG
  native:
    container-build: false

model:
  path: ${MODEL_PATH:model/yolov5x6.torchscript.zip}
  name: ${MODEL_NAME:yolov5x6.torchscript}

env:
  debug: false

video:
  path: examples/example.avi